spring:
  application:
    name: YGTM
  datasource:
    url: jdbc:postgresql://localhost:5432/ygtm-db
    username: ygtm
    password: ygtm
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080