version: "3.9"
services:
  db:
    image: postgres:15
    container_name: ygtm_container
    environment:
      POSTGRES_USER: ygtm
      POSTGRES_PASSWORD: ygtm
      POSTGRES_DB: ygtm-db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: